---
title: "Iteration and List Cols"
author: "Mia Isaacs"
date: "2024-10-29"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample = runif(100),
  mat = matrix(1:8, nrow = 2, ncol = 4, byrow = TRUE),
  summary = summary(rnorm(1000))
)

print(l)
l[["mat"]][1,3]
```

make a list that's a bit more useful

```{r}
list_norm =
  list(
    a = rnorm(20,0,5),
    b = rnorm(20,4,5),
    c = rnorm(20,0,10),
    d = rnorm(20,4,10)
  )

list_norm[["a"]]
```

let's reuse the function we wrote

```{r}
mean_and_sd = function(x) {

  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df =
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  return(out_df)

}
```

let's use the function to take mean and sd of all samples

```{r}
mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])
```

## use for a loop

create output list and run for a loop

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  
}

output
```




